### PR TITLE
new mrset feature

### PR DESCRIPTION
**Pull request by ofajardo**

### CODE REVIEW

**Comment by slobodan-ilic** [comment]
So this is now in `dev` @ofajardo ? Are we good to replace our forked repo with this official one? Maybe some ideas when this could be part of official release?

**Comment by slobodan-ilic** [comment]
Great, thanks so much!

**Comment by slobodan-ilic** [comment]
Hey @ofajardo, is there any news on that conda thing hopefully being resolved? We're just starting the switch from fork back to your repo, and a release would be fantastic!!!

**Comment by ofajardo** [comment]
@slobodan-ilic The conda thing is queued for a bot rerun, but still has not been run/solved unfortunately. They said it is a big migration going on on their side, and that it would take a while.

**Comment by ofajardo** [comment]
@slobodan-ilic new reelase 1.2.8 is out! at least in pypi, hopefully tomorrow or so should be in conda as well, if everything goes well!

**Comment by GrantDickerson** [comment]
Hi y'all, just a quick note from out in the wild to report that it is working...through an extraordinary coincidence, I seem to have needed this for the first time in years within hours of the old problem being solved, and I'm seeing exactly what I would expect.  Appreciate your work, and so does my team for the large amount of labor hours this is about to save them.

**Pull request merged**
